#:schema node_modules/wrangler/config-schema.json
name = "pokeprompt-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[vars]
CORS_ORIGIN = "https://pokeprompt.pages.dev"
